-- creation de la table utilisateurs
CREATE TABLE utilisateurs (
	id bigserial NOT NULL,
	nom varchar NULL,
	prenom varchar NULL,
	email varchar NOT NULL,
	mot_de_passe varchar NOT NULL,
	CONSTRAINT utilisateurs_pk PRIMARY KEY (id),
	CONSTRAINT utilisateurs_un UNIQUE (email)
);

-- insertion des données
INSERT INTO utilisateurs (nom,prenom,email,mot_de_passe) VALUES 
('DOE','John','john.doe@les-enovateurs.com','azerty')
,('DOE','Louise','louise.doe@les-enovateurs.com','uiopq')
,('DOE','Sébastien','sebastien.doe@les-enovateurs.com','qsdf')
,('DOE','Camille','camille.doe@les-enovateurs.com','ghjk')
,('DOE','Damien','damien.doe@les-enovateurs.com','lmwx')
,('DOE','Sandrine','sandrine.doe@les-enovateurs.com','cvbn')
,('DOE','Philippe','philippe.doe@les-enovateurs.com','mlkj');

INSERT INTO utilisateurs (nom,prenom,email,mot_de_passe) VALUES ('Kibo','Shelby','libero@sociisnatoquepenatibus.edu','6541'),('Bernard','Kiona','felis.eget.varius@lacinia.net','9530'),('Carl','Paloma','Praesent.eu@orcilobortisaugue.org','3093'),('Xenos','Cathleen','quis.pede.Suspendisse@ipsum.edu','6521'),('Sebastian','Tatyana','a.ultricies@mollisnec.co.uk','5204'),('Oleg','Kylee','ante.Maecenas@variusorci.org','9299'),('Lars','Irene','lacus.pede.sagittis@eutemporerat.org','2385'),('Baker','Constance','ut.odio@ligulaNullamfeugiat.ca','9687'),('Martin','Vivien','in@dolorFusce.co.uk','3010'),('Castor','Harriet','massa@utdolordapibus.net','7758');
INSERT INTO utilisateurs (nom,prenom,email,mot_de_passe) VALUES ('Colt','Latifah','odio@consequat.edu','2702'),('Brandon','Lillian','molestie.sodales@leoin.org','8459'),('Kyle','Willow','Quisque.purus.sapien@turpisnec.ca','7544'),('Lee','Kirby','in.molestie@tinciduntcongueturpis.com','9713'),('Baker','Anika','Aenean@ornarelibero.org','2817'),('Dorian','Ciara','consectetuer.ipsum@vestibulum.ca','7402'),('Channing','Jorden','nec@PhasellusornareFusce.co.uk','3224'),('Jakeem','Taylor','adipiscing.elit.Etiam@justosit.co.uk','3604'),('Jamal','Penelope','a.ultricies@sed.net','8593'),('Davis','Sara','gravida.molestie.arcu@inlobortis.ca','7320');
INSERT INTO utilisateurs (nom,prenom,email,mot_de_passe) VALUES ('Jeremy','Bethany','Sed@facilisis.org','3808'),('Eaton','Deanna','risus@justoeu.net','2422'),('Amir','Angelica','venenatis.a.magna@Fuscediamnunc.org','6573'),('Francis','Lee','velit@conubianostra.net','3668'),('Hilel','Carissa','nisi.Cum@etmalesuada.edu','7256'),('Joel','Riley','quis.accumsan@rutrumFuscedolor.ca','4164'),('Otto','Cathleen','aliquet.odio@necdiam.ca','8424'),('Kaseem','Dakota','vel.arcu@veliteget.com','3848'),('Noah','Giselle','at.iaculis.quis@diamDuismi.ca','9517'),('Mark','Jordan','Nunc.pulvinar.arcu@aliquam.org','6157');
INSERT INTO utilisateurs (nom,prenom,email,mot_de_passe) VALUES ('Gregory','Maxine','risus@risusDonecegestas.ca','5025'),('Geoffrey','Lucy','consequat.lectus.sit@disparturientmontes.org','9728'),('Armand','Regan','euismod.est.arcu@adui.co.uk','7425'),('Jack','Yolanda','diam@Phasellusataugue.ca','8182'),('Jared','Melyssa','nonummy@Etiam.com','9373'),('Melvin','Hadassah','volutpat.nunc.sit@bibendum.net','4481'),('Rigel','Libby','mattis@laciniaorciconsectetuer.co.uk','5939'),('Bernard','Fay','feugiat@non.ca','4728'),('Hiram','Courtney','dignissim.magna.a@infaucibus.net','1492'),('Porter','Breanna','facilisis.eget.ipsum@portaelita.com','5520');
INSERT INTO utilisateurs (nom,prenom,email,mot_de_passe) VALUES ('Nigel','Wanda','volutpat.Nulla@sitametconsectetuer.com','2954'),('Uriah','Mariko','Vivamus.euismod@nonmassanon.net','6799'),('Kirk','Zelda','molestie.tellus.Aenean@odio.ca','8883'),('Malcolm','Whoopi','ac.arcu@laoreetlibero.ca','4174'),('Quamar','Yeo','a.nunc@blanditNamnulla.org','3843'),('Curran','Taylor','consectetuer.euismod@venenatislacus.net','8274'),('Lucian','Amy','nisi@diamluctuslobortis.org','1513'),('Vladimir','Xerxes','pede@semegestasblandit.ca','7121'),('Derek','Kirsten','purus.Nullam@gravidaAliquam.edu','3175'),('Grant','Lacey','vulputate@quamvelsapien.com','2008');
INSERT INTO utilisateurs (nom,prenom,email,mot_de_passe) VALUES ('Timon','Sloane','facilisis.eget.ipsum@lobortis.org','9933'),('Lionel','Destiny','Duis.sit.amet@eudoloregestas.co.uk','9404'),('Kuame','Brielle','sit.amet@ipsum.edu','3280'),('Prescott','Jamalia','nec.imperdiet.nec@Crasdolordolor.ca','1996'),('Hu','Keiko','ligula.Donec.luctus@vel.org','5336'),('Cain','Donna','ipsum@idante.ca','4006'),('Vaughan','Ria','nascetur.ridiculus@lobortisultricesVivamus.net','5362'),('Herman','Roanna','et.euismod@volutpatornarefacilisis.com','8482'),('Maxwell','Maile','ligula.elit@fermentumconvallis.com','6156'),('Levi','Emma','nibh.Phasellus.nulla@fermentumfermentum.com','2431');
INSERT INTO utilisateurs (nom,prenom,email,mot_de_passe) VALUES ('Zane','Kitra','et.lacinia@enimnonnisi.co.uk','6501'),('Lane','Veronica','Mauris.vestibulum@vitaesodales.org','8698'),('Merrill','Venus','orci@sedhendrerit.com','1142'),('Bruce','Ifeoma','non.massa.non@duiinsodales.ca','5724'),('Nehru','Evangeline','litora.torquent.per@lacusNullatincidunt.co.uk','5941'),('Tate','Vanna','pharetra.Nam@eumetus.com','2507'),('Kaseem','Rose','nec.tempus.mauris@nunc.com','9177'),('Emery','Hedy','diam@sitamet.edu','7365'),('Oren','Charde','semper.auctor@purus.co.uk','5585'),('Tiger','Adara','massa.rutrum@ultricesiaculisodio.co.uk','4393');
INSERT INTO utilisateurs (nom,prenom,email,mot_de_passe) VALUES ('Nathan','Octavia','nisi.a.odio@Duisa.co.uk','3605'),('Vernon','Cassady','purus.sapien.gravida@Inscelerisque.ca','8718'),('Brett','Yetta','risus.a@varius.co.uk','2561'),('Nicholas','Imogene','vulputate.posuere.vulputate@dui.edu','7840'),('Salvador','Naomi','euismod.enim@ipsum.edu','5978'),('John','Jade','tortor.at@risus.net','1263'),('Burke','Sonya','lacus.Aliquam@eu.com','4030'),('Rashad','Cherokee','purus@purusmauris.ca','3887'),('Zachary','Cathleen','euismod@mi.net','6778'),('Devin','Odessa','pede@erosNam.ca','4481');
INSERT INTO utilisateurs (nom,prenom,email,mot_de_passe) VALUES ('Neville','Shelly','dui@et.co.uk','6935'),('Leo','Xantha','nunc@utnisia.org','3833'),('Dante','Ursula','sit.amet.consectetuer@netus.ca','9237'),('Elijah','Dakota','lobortis.quis.pede@fringilla.com','9838'),('Lucas','Keiko','egestas.a.dui@auctor.net','6200'),('Colton','Paloma','lacinia@at.com','8221'),('Abdul','Catherine','pellentesque.tellus@in.co.uk','4414'),('Peter','Montana','faucibus.Morbi@neque.com','4359'),('Emery','Doris','diam.eu@eueuismod.edu','4276'),('Burke','Cassidy','turpis.egestas@mollisIntegertincidunt.co.uk','1590');
INSERT INTO utilisateurs (nom,prenom,email,mot_de_passe) VALUES ('Ali','Yvonne','non.hendrerit@et.org','8015'),('Harper','Charde','Maecenas.ornare.egestas@estNunc.ca','5408'),('Tiger','Xantha','sed.dui@Phasellus.co.uk','4507'),('Sawyer','Tatyana','lacus.varius@dignissimlacus.co.uk','2368'),('Hammett','Liberty','et@Nunc.org','2263'),('Holmes','Virginia','massa.lobortis.ultrices@velitin.org','9361'),('Alec','Cassady','Sed@ridiculusmus.net','2226'),('Benedict','Macy','Sed.eu@pedePraesenteu.edu','2547'),('Reese','Rowan','Aliquam.erat.volutpat@odio.ca','2483'),('Paki','Uta','nulla.at.sem@nullaInteger.com','9412');
