version: '3.2'

networks:
  phalcon-network:
    driver: bridge
services:
  phalcon-db:
    image: postgres:10.8-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:Z
      - ./init_db_data.sql:/docker-entrypoint-initdb.d/init_db_data.sql
    networks:
      - phalcon-network
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: phalcon
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_statement=all
  
  phalcon-web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - env=dev
        - phalcon_version=v4.0.1
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./www/
        target: /var/www/html
    networks:
      - phalcon-network
    working_dir: /var/www/html
    depends_on:
      - phalcon-db
